[module.hugoVersion]
extended = true
min = "0.111.3"

[[module.imports]]
path = "github.com/hugomods/hugopress"

[[module.imports]]
path = "github.com/hugomods/base"

[[module.imports]]
path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"

[params.hugopress.modules.hb.hooks.head-begin]

[params.hugopress.modules.hb.hooks.head-end]
cacheable = true

[params.hugopress.modules.hb.hooks.body-end]
cacheable = true
weight = 1000

[params.hb]
css_bundle_name = "hb"
js_bundle_name = "hb"
