[module.hugoVersion]
extended = true
min = "0.134.0"

[[module.imports]]
path = "github.com/hugomods/hugopress"

[[module.imports]]
path = "github.com/hugomods/base"

[[module.imports]]
path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"

[params.hugopress.modules.hb.attributes.document]
cacheable = true

[params.hugopress.modules.hb.attributes.body]

[params.hugopress.modules.hb.attributes.hb-main]

[params.hugopress.modules.hb.attributes.hb-alias-refresh-meta]

[params.hugopress.modules.hb.hooks.head-begin]
cacheable = true

[params.hugopress.modules.hb.hooks.head-end]
cacheable = true

[params.hugopress.modules.hb.hooks.body-end]
cacheable = true
weight = 1000

[params.hb]
css_bundle_name = "hb"
js_bundle_name = "hb"
logo = "/images/logo.png"
color = "light" # default color mode, light or dark.
sass_transpiler = "dartsass" # dartsass or libsass (deprecated).
sass_silence_deprecations = ["import", "global-builtin", "color-functions"]

[params.hb.styles]
prefix = "hb-" # CSS variables prefix.
# primary = "#0d6efd" # hex color code.
hb_top_offset = "24px" # the default top offset, in pixels, for internal use.

[params.hb.tables]
align = "" # vertical alignment: top, middle or bottom.
bordered = true
border_style = "" # similar to the style.
group_divider = false
hover = true
striped = true
striped_columns = false
style = "" # light, dark, primary, success, warning, danger and so on.
thead_style = "" # similar to the style.

[params.hb.blockquotes]
bordered = true
border_width = 4 # 1-5.
border_style = "primary"
